# tf.clip_by_value（）函数

In [1]:
import tensorflow as tf
sess=tf.InteractiveSession()

C:\Program Files (x86)\software\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# 定义一个list，填入一些数据
a=[1.0,2.0,3.1,4.3,5.6,2.4,6.7,1e-6,1e-7,0]

### 使用tf.clip_by_value函数进行处理，并返回处理过的tensor
### clip_by_value(t, clip_value_min, clip_value_max,name=None)
### t：待处理的tensor，或是一个list等
### clip_value_min：需要过滤的最小值，若t中存在比该值还小的值，一律换成clip_value_min
### clip_value_max：需要过滤的最大值，若t中存在比该值还大的值，一律换成clip_value_max
### name：名称 

In [3]:
a=tf.clip_by_value(a,1e-5,5.0)
print(a.eval())

[1.0e+00 2.0e+00 3.1e+00 4.3e+00 5.0e+00 2.4e+00 5.0e+00 1.0e-05 1.0e-05
 1.0e-05]


# tf.log（）函数
## 以自然底数e为底求log
## log(x, name=None)
## x:待处理的数据，可以是一个数字，或是一个list，一个tensor
## name:名称

In [5]:
# tf.log处理数字
a=tf.log(3.2)
print(a.eval())

# 定义一个list。注意：这里1e3中的e表示的是底数为10，即1e3 = 1000
b = [1.2,3.5,1.0,33.0,4.5,1e3]
# 处理并输出
print(tf.log(b).eval())

1.1631508
[0.1823216 1.252763  0.        3.4965076 1.5040774 6.9077554]


## tf.random_normal（）函数 
## 此函数用于生成一个满足正态分布的随机矩阵。

In [6]:
# 定义一个4*4大小的满足正态分布的随机数矩阵的tensor
# random_normal(shape,mean=0.0,stddev=1.0,dtype=dtypes.float32,seed=None,name=None)
# shape:需要使用的矩阵的大小，
# mean:定义该正态分布的均值，默认为0.0
# stddev:定义该正态分布的标准差，默认为1.0
# dtype:定义该正态函数需要返回的数据类型，默认为dtypes.float32
# seed:随机数种子
# name:名称

a = tf.random_normal(shape=[4,4],mean=0.0,stddev=1.0,dtype=tf.float32)

# 初始化全局变量，这里初始化变量a
# 注意：上面的代码只是定义了一个正态分布的tensor，并没有对其进行初始化操作。
tf.global_variables_initializer().run()

# 输出结果
print(a.eval())

[[ 0.42103493 -0.78315014 -0.6630816  -1.0379691 ]
 [-0.34434092  0.70581454  0.42035937 -1.4615947 ]
 [-0.06307134 -2.0253668   1.5485874  -0.17265217]
 [-0.7624369  -0.7700588   0.9921296   0.06359687]]


# tf.truncated_normal（）函数 
此函数生成一个满足正态分布的随机矩阵，但是若随机出来的值偏离平均值超过2个标准差，那么这个数将会被重新随机。

In [7]:
# 定义一个4*4大小的满足正态分布的随机数矩阵的tensor,
# 若随机出来的值偏离平均值超过2个标准差，这个数将会被重新随机。
# truncated_normal(shape,mean=0.0,stddev=1.0,dtype=dtypes.float32，
#                  seed=None,name=None)
# shape:需要使用的矩阵的大小
# mean:定义该正态分布的均值，默认为0.0
# stddev:定义该正态分布的标准差，默认为1.0
# dtype:定义该正态函数需要返回的数据类型，默认为dtypes.float32
# seed:随机数种子
# name:名称

a = tf.truncated_normal(shape=[4,4],mean=0.0,stddev=1.0,dtype=tf.float32)

# 初始化全局变量，这里初始化变量a
# 注意：上面的代码只是定义了一个正态分布的tensor，并没有对其进行初始化操作。
# tf.global_variables_initializer().run()

# 输出结果
print(a.eval())

[[-0.15586424  1.6567829  -1.6921844  -0.19512472]
 [-0.5914971   1.0176795   0.49398646  0.9999007 ]
 [-0.9362021  -0.16295558 -0.24245857 -0.377929  ]
 [-1.0768274   1.1443577   0.2604361   1.8684555 ]]


# tf.random_uniform（）函数 
生成的值遵循“[minval，maxval)”范围内的均匀分布。 下限“minval”包含在范围内，而上限“maxval”被排除。

对于浮点数，默认范围是[0，1）。 对于int，至少必须明确指定maxval。

在整数的情况下，随机整数稍微有偏差，除非’maxval - minval`是两个精确的幂。 对于“maxval - minval”的值，偏差小于输出范围（“2^32”或“2^64”）的偏差。

In [8]:
# 定义一个4*4大小的满足平均分布的随机数矩阵tensor
# random_uniform(shape,minval=0,maxval=None,dtype=dtypes.float32,seed=None,name=None)
# shape:需要使用的矩阵的大小，
# minval:定义该平均分布的所使用的最小值，默认为0
# maxval:定义该平均分布的所使用的最大值，默认为None
# dtype:定义该平均分布需要返回的数据类型，默认为dtypes.float32
# seed:随机数种子
# name:名称

a = tf.random_uniform(shape=[4,4],minval=-1.0,maxval=3.0,dtype=tf.float32)

# 初始化全局变量，这里初始化变量a
# 注意：上面的代码只是定义了一个平均分布的tensor，并没有对其进行初始化操作。
tf.global_variables_initializer().run()

# 输出结果
print(a.eval())

[[-0.4210019  -0.24430275 -0.21048164  0.8688102 ]
 [ 2.6851234   1.0655475   0.00552797  0.9640131 ]
 [-0.7852216   1.7720866   2.593194    1.0956802 ]
 [ 0.61841536  1.25242     2.3069081   1.4856901 ]]


# tf.zeros（）和tf.ones（）函数

In [9]:
# 返回一个指定大小矩阵的全为0的tensor
# zeros(shape, dtype=dtypes.float32, name=None)
# shape :需要使用的矩阵的大小
# dtype :需要使用的数据的类型，默认为dtype.float32
# name :名称
a = tf.zeros(shape=[4,4],dtype=tf.float32)

# 返回一个指定大小矩阵的全为1的tensor
# ones(shape, dtype=dtypes.float32, name=None)
# shape :需要使用的矩阵的大小
# dtype :需要使用的数据的类型，默认为dtype.float32
# name :名称
b = tf.ones(shape=[4,4],dtype=tf.float32)

# 初始化全局变量
tf.global_variables_initializer().run()

# 输出a
print("a矩阵如下:\n",a.eval())

# 输出b
print("b矩阵如下:\n",b.eval())

a矩阵如下:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
b矩阵如下:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# tf.zeros()和tf.ones()更多的时候用来对变量进行初始化，如：
# 返回一个指定大小矩阵的全为0的tensor变量a
a = tf.Variable(tf.zeros(shape=[5,5],dtype=tf.float32))

# 初始化全局变量
tf.global_variables_initializer().run()

# 输出a
print("变量a矩阵如下:\n",a.eval())

变量a矩阵如下:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# tf.fill（）函数 
此函数创建并返回一个指定维度的矩阵的tensor，并填充指定的数值。

In [11]:
# 返回一个指定大小矩阵的全为0的tensor变量a
# fill(dims, value, name=None)
# dims:指定生成的矩阵的维度
# value:指定生成的矩阵的数值
# name:名称

a = tf.fill(dims=[3,4],value=9.0)

b = tf.fill(dims=[3,4,5],value=8)

# 初始化全局变量
tf.global_variables_initializer().run()

# 输出a
print("a矩阵如下:\n",a.eval())

# 输出b
print("b矩阵如下:\n",b.eval())

a矩阵如下:
 [[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]
b矩阵如下:
 [[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]]


# tf.constant（）函数 
此函数创建一个常量tensor。这个常量可以使数字，字符串，list等数据类型。

In [12]:
# constant(value, dtype=None, shape=None, name="Const", verify_shape=False)
#
# 结果tensor使用`dtype`类型的值填充，由参数`value`和（可选）`shape`指定（见下面的例子）。
#
# 参数`value`可以是一个常量值，也可以是'dtype'类型的值列表。 如果“value”是一个list，则list的长度必须小于或等于“shape”参数（如果指定）隐含的元素数。 在列表长度小于“shape”指定的元素数量的情况下，列表中的最后一个元素将用于填充剩余的条目。
#
# 参数`shape`是可选的。 如果存在，它指定所得张量的尺寸。 如果不存在，则使用“value”的形状。
#
# 如果没有指定参数`dtype`，那么从`value`的类型推断出类型。
#
# value:输出类型为'dtype'的常量值（或list）。
# dtype:所得tensor的元素的类型。
# shape:所得tensor的可选尺寸。
# name:tensor的可选名称。
# verify_shape:启用验证值形状的布尔值

# 定义一个数值型常量
a = tf.constant(10.0 ,dtype=tf.float32)

# 定义一个string类型的字符串常量
b = tf.constant("hello world!",dtype=tf.string)

# 定义一个矩阵常量，参考shape参数
c = tf.constant([1.0,2.0,3.0,4.0,5.0,6.0], dtype=tf.float32,shape=[3,2])

# 定义一个填充的矩阵变量
d = tf.constant(-2.0,dtype=tf.float32, shape=[3,3])

tf.global_variables_initializer().run()

# 输出
print("a:\n",a.eval())

print("b:\n",b.eval())

print("c:\n",c.eval())

print("d:\n",d.eval())

a:
 10.0
b:
 b'hello world!'
c:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
d:
 [[-2. -2. -2.]
 [-2. -2. -2.]
 [-2. -2. -2.]]


# tf.greater（）函数 
tf.greater:对两个tensor或是list依次对每个元素进行比较，并返回相应的bool值。与此类似的还有tf.greater_equal（）、tf.less（）、tf.less_equal（）。 
下面的实例以tf.greater（）函数为例。 
注意：比较的两个tensor的维度必须相同，否则会报错。

In [13]:
# 定义两个list
a = [1   ,2  ,43  ,3.4 ,5.3 ,324 ,4 ]
b = [2.2 ,34 ,3.4 ,4.4 ,3   ,56  ,8 ]

# greater(x, y, name=None)
# x: 一个 tensor或是一个list等。数据必须是以下的数据类型: `float32`, `float64`, `int32`, `int64`, `uint8`, `int16`, `int8`, `uint16`, `half`.
# y: 一个 tensor或是一个list等，需要和x保持同样的数据类型。
c = tf.greater(a,b)

# 输出
print(c.eval())

[False False  True False  True  True False]
