In [1]:
import numpy as np

In [5]:
arr1=np.arange(12).reshape((3,4))
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
arr2,arr3=np.split(arr1,2,axis=1)#垂直方向分割，分成两份
print(arr2)
print(arr3)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [11]:
arr4,arr5,arr6=np.split(arr1,3,axis=0)#水平方向方向分割，分成三份
print(arr4)
print(arr5)
print(arr6)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [13]:
arr7,arr8,arr9=np.split(arr1,3,axis=1)#垂直方向分割，分成三份

ValueError: array split does not result in an equal division

In [15]:
arr7,arr8,arr9=np.array_split(arr1,3,axis=1)#垂直方向分割，分成三份,不等分割
print(arr7,arr8,arr9)

[[0 1]
 [4 5]
 [8 9]] [[ 2]
 [ 6]
 [10]] [[ 3]
 [ 7]
 [11]]


In [17]:
arr7,arr8,arr9=np.vsplit(arr1,3)#垂直分割
print(arr7)
print(arr8,'\n',arr9)

[[0 1 2 3]]
[[4 5 6 7]] 
 [[ 8  9 10 11]]


In [19]:
arr7,arr8=np.hsplit(arr1,2)#水平分割
print(arr7)
print(arr8)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]
