In [1]:
import numpy as np

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr4=np.vstack((arr1,arr2,arr3))#垂直合并
print(arr4)
print(arr4.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
arr5=np.hstack((arr1,arr2,arr3))#水平合并
print(arr5)

[1 2 3 4 5 6 7 8 9]


In [13]:
arrv=np.vstack((arr1,arr2,arr3))
print(arrv)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arrh=np.hstack((arr1,arr2,arr3))
print(arrh)

[1 2 3 4 5 6 7 8 9]


In [20]:
arr=np.concatenate((arr1,arr2,arr1))#默认水平合并
print(arr)

[1 2 3 4 5 6 1 2 3]


In [29]:
arr=np.concatenate((arr4,arrv),axis=1)#合并的array的维度要相同，array形状要匹配，axis横向合并
print(arr)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [31]:
arr=np.concatenate((arr4,arrv),axis=0)#合并的array的维度要相同，array形状要匹配，axis纵向合并
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
arr1.T
#一维的array不能转置

array([1, 2, 3])

In [33]:
print(arr1.shape)

(3,)


In [35]:
arr_1=arr1[np.newaxis,:]
print(arr_1)#变成了二维的,1行3列
print(arr_1.shape)

[[1 2 3]]
(1, 3)


In [37]:
print(arr_1.T)#转置之后也发生了变化

[[1]
 [2]
 [3]]


In [38]:
arr1_2=arr1[:,np.newaxis]#3行1列
print(arr1_2)
print(arr1_2.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [40]:
arr1_3=np.atleast_2d(arr1)#至少变为二维的数据
print(arr1_3)
print(arr1_3.shape)

[[1 2 3]]
(1, 3)


In [41]:
arr1_4=np.atleast_3d(arr1)#至少变为三维的数据
print(arr1_4)
print(arr1_4.shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)
