In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
arr2=arr1#指共同一块内存，浅拷贝
arr2[0]=5
print(arr1)
print(arr2)

[5 2 3]
[5 2 3]


In [4]:
arr3=arr1.copy()#深拷贝
arr3[0]=10
print(arr1)
print(arr3)

[5 2 3]
[10  2  3]


In [5]:
n = 3
res =  np.array([[0] * n] * n)
print(res)
print(id(res[0][0]),id(res[1][0]),id(res[0][1]))
k = 1
for i in range(n):    
    for j in range(n):
        res[i][j] = k
        k += 1
print(res)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
123679104 123679104 123679104
[[1 2 3]
 [4 5 6]
 [7 8 9]]
