In [2]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot=arr[len(arr)/2]
    left=[x for x in arr if x <pivot]
    middle=[x for x in arr if x==pivot]
    right=[x for x in arr if x>pivot]
    return quicksort(left) +middle +quicksort(right)

In [11]:
x=3
print(type(x))

print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)
print('*************************')
x+=1
print(x)
x*=2
print(x)
print('***************************')
y=2.5
print(y,'\t',y+1,'\t',y*2,'\t',y**2)

<class 'int'>
3
4
2
6
9
*************************
4
8
***************************
2.5 	 3.5 	 5.0 	 6.25


In [13]:
#Booleans：Python的布尔型逻辑和其他语言都一样，
t=True
f=False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print( t !=f)

<class 'bool'>
False
True
False
True


In [16]:
#Strings:Python对字符型的支持非常强大。
hello='hello'
world='world'
print(hello)
print(world)
print(len(hello))
hw=hello + '' +world
print(hw)
hw12='%s %s %12d' %(hello,world,12)#打印为文字和数字
print(hw12)

hello
world
5
helloworld
hello world           12


In [20]:
s='hello'
print(s.capitalize())
print(s.upper())
print(s.lower())
print(s.rjust(7))#向右调整7个bit
print(s.center(7))
print(s.replace('l','a'))
print('fd fffff fff'.strip())

Hello
HELLO
hello
  hello
 hello 
heaao
fd fffff fff


In [21]:
# Containers:Python包含了几个内置的容器类型：lists, dictionaries, sets, and tuples
# Lists:list在Python中几乎等价于数组，但是是可调整大小的同时也可以包容不同类型的元素。
xs=[3,1,2]
print(xs,xs[2])
print(xs[-1])
xs[2]='fool'
print(xs)
xs.append('bar')
print(xs)
x=xs.pop()
print(x,xs)

[3, 1, 2] 2
2
[3, 1, 'fool']
[3, 1, 'fool', 'bar']
bar [3, 1, 'fool']


In [9]:
#Slicing：除了每次访问一个列表元素，Python还提供了一种简洁的语法去访问子列表，这被称为slicing:
nums=range(5)
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
#nums[2:4]=[8, 9]
print(nums)

range(0, 5)
range(2, 4)
range(2, 5)
range(0, 2)
range(0, 5)
range(0, 4)
range(0, 5)


In [27]:
animals=['cat','dog','pig']
for idx ,animal in enumerate(animals):
    print('%d: %s' %(idx,animal))#打印文字、数字的一种方式
    

0: cat
1: dog
2: pig


In [3]:
 import numpy as np
    

In [33]:
sample1=np.random.random((3,2))#生成3行2列从0到1的随机数
print(sample1)

[[ 0.01072728  0.26539607]
 [ 0.06802829  0.10066067]
 [ 0.12577319  0.14549275]]


In [7]:
sample2=np.random.normal(size=(3,2))#生成符合正态分布的随机数
print(sample2)

[[-0.20233037  0.40804388]
 [-1.03352091 -0.21774014]
 [ 0.15115407  2.22703598]]


In [8]:
sample3=np.random.randint(0,10,size=(3,2))#生成3行2列从0到100的随机整数
print(sample3)

[[8 1]
 [5 8]
 [3 4]]


In [10]:
np.sum(sample3)#求和

29

In [11]:
np.min(sample3)#求最小值

1

In [12]:
np.max(sample3)#求最大值

8

In [13]:
np.sum(sample3,axis=0)#对列求和

array([16, 13])

In [14]:
np.sum(sample3,axis=1)#对行求和

array([ 9, 13,  7])

In [15]:
np.argmin(sample3)#求最小值的索引

1

In [16]:
np.argmax(sample3)#求最大值的索引

0

In [21]:
# 求元素的平均值的两种方式
print(np.mean(sample3))
print(sample3.mean())

4.83333333333
4.83333333333


In [23]:
#求中位数
np.median(sample3)

4.5

In [24]:
#求开方
np.sqrt(sample3)

array([[ 2.82842712,  1.        ],
       [ 2.23606798,  2.82842712],
       [ 1.73205081,  2.        ]])

In [26]:
sample4=np.random.randint(0,10,size=(1,10))
print(sample4)

[[0 4 1 1 6 2 2 2 8 6]]


In [27]:
np.sort(sample4)

array([[0, 1, 1, 2, 2, 2, 4, 6, 6, 8]])

In [28]:
print(sample3)
print(np.sort(sample3))#按行从小到大排序

[[8 1]
 [5 8]
 [3 4]]
[[1 8]
 [5 8]
 [3 4]]


In [29]:
np.clip(sample4,2,7)#小于2的变成2，大于的变成7

array([[2, 4, 2, 2, 6, 2, 2, 2, 7, 6]])