In [1]:
import numpy as np


In [3]:
# itwise_and
# 通过np.bitwise_and()函数对输入数组中的整数的二进制表示的相应位执行位与运算。
print('13 和17 的二进制')
a,b=13,17
print(bin(a),bin(b))
print('\n')

print('13和17的位与')
print(np.bitwise_and(13,17))

13 和17 的二进制
0b1101 0b10001


13和17的位与
1


In [4]:
# bitwise_or
# 通过np.bitwise_or()函数对输入数组中的整数的二进制表示的相应位执行位或运算。
a,b=13,17
print('13 和 17的二进制')
print(bin(a),bin(b))

print('13 和17的位或')
print(np.bitwise_or(13,17))


13 和 17的二进制
0b1101 0b10001
13 和17的位或
29


In [9]:
# invert
# 此函数计算输入数组中整数的位非结果。 对于有符号整数，返回补码。
print('13的位反转 ，其中ndarray 的dtype是unit8')
print(np.invert(np.array([13],dtype=np.uint8)))
#比较13 和 242的二进制表示，我们发现了位的反转
print('13的二进制表示')
print(np.binary_repr(13,width=8))
print('\n')

print('242的二进制表示')
print(np.binary_repr(242,width=8))

13的位反转 ，其中ndarray 的dtype是unit8
[242]
13的二进制表示
00001101


242的二进制表示
11110010


In [10]:
# left_shift
# numpy.left shift()函数将数组元素的二进制表示中的位向左移动到指定位置，右侧附加相等数量的 0。
print('将10左移两位：')
print(np.left_shift(10,2))
print('\n')

print('10的二进制表示')
print(np.binary_repr(10,width=8))

print('40的二进制表示')
print(np.binary_repr(40,width=8))
# '00000101' 中的两位移动到了左边，并在右边添加了两个0

将10左移两位：
40


10的二进制表示
00001010
40的二进制表示
00101000


In [11]:
# ight_shift
# numpy.right_shift()函数将数组元素的二进制表示中的位向右移动到指定位置，左侧附加相等数量的 0。
print('将40右移两位')
print(np.right_shift(40,2))
print('\n')

print('40的二进制表示')
print(np.binary_repr(40,width=8))
print('\n')

print('10的二进制表示')
print(np.binary_repr(10,width=8))

将40右移两位
10


40的二进制表示
00101000


10的二进制表示
00001010


In [12]:
# NumPy - 字符串函数
# 以下函数用于对dtype为numpy.string_或numpy.unicode_的数组执行向量化字符串操作。 它们基于 Python 内置库中的标准字符串函数。


# numpy.char.add()
# 函数执行按元素的字符串连接。
print('连接两个字符串')
print(np.char.add(['hello'],['xyz']))
print('\n')
print('连接示例')
print(np.char.add(['hello','hi'],['abc','xyz']))

连接两个字符串
['helloxyz']


连接示例
['helloabc' 'hixyz']


In [21]:
# numpy.char.multiply()
# 这个函数执行多重连接。
print(np.char.multiply('Hello',3))

# numpy.char.center()
# 此函数返回所需宽度的数组，以便输入字符串位于中心，并使用fillchar在左侧和右侧进行填充。
print(np.char.center('hello',20,fillchar='*'))

# numpy.char.capitalize()
# 函数返回字符串的副本，其中第一个字母大写
print(np.char.capitalize('hello world'))

# numpy.char.title()
# 返回输入字符串的按元素标题转换版本，其中每个单词的首字母都大写。
print(np.char.title('how are you?'))

# numpy.char.lower()
# 函数返回一个数组，其元素转换为小写。它对每个元素调用str.lower
print(np.char.lower(['HEllo']))
print(np.char.lower('FGFDG'))

HelloHelloHello
*******hello********
Hello world
How Are You?
['hello']
fgfdg


In [22]:
# numpy.char.upper()
# 函数返回一个数组，其元素转换为大写。它对每个元素调用str.upper
print(np.char.upper('hello'))
print(np.char.upper(['hello','world']))

HELLO
['HELLO' 'WORLD']


In [23]:
# numpy.char.upper()
# 函数返回一个数组，其元素转换为大写。它对每个元素调用str.upper
print(np.char.split('hello how are you?'))
print(np.char.split('ssfdsfdsdd,sfdfsfdsfd,sdsfdfdsfdd'))

['hello', 'how', 'are', 'you?']
['ssfdsfdsdd,sfdfsfdsfd,sdsfdfdsfdd']


In [24]:
# numpy.char.splitlines()
# 函数返回数组中元素的单词列表，以换行符分割。
print(np.char.splitlines('hello\nhow are you'))

['hello', 'how are you']


In [30]:
# numpy.char.strip()
# 函数返回数组的副本，其中元素移除了开头或结尾处的特定字符。
print(np.char.strip('ddsd  ghbgs  d','dsds'))#包含ds的都被过滤掉了
print(np.char.strip(['dffd ','ahiaooo dd','fdff'],'a'))

  ghbgs  
['dffd ' 'hiaooo dd' 'fdff']


In [36]:
# numpy.char.join()
# 这个函数返回一个字符串，其中单个字符由特定的分隔符连接。
print(np.char.join(':','DMY'))
print(np.char.join([':','-'],['dmy','ymd']))


D:M:Y
['d:m:y' 'y-m-d']


In [37]:
# numpy.char.replace()
# 这个函数返回字符串副本，其中所有字符序列的出现位置都被另一个给定的字符序列取代。
print(np.char.replace('he is a good boy','is','was'))

he was a good boy


In [38]:
# numpy.char.decode()
# 这个函数在给定的字符串中使用特定编码调用str.decode()
a=np.char.encode('hello','cp500')
print(a)
print(np.char.decode(a,'cp500'))

b'\x88\x85\x93\x93\x96'
hello


In [39]:
# numpy.char.encode()
# 此函数对数组中的每个元素调用str.encode函数。 默认编码是utf_8，可以使用标准 Python 库中的编解码器。
a=np.char.encode('hello','cp500')
print(a)

b'\x88\x85\x93\x93\x96'


In [40]:
# 三角函数
# NumPy 拥有标准的三角函数，它为弧度制单位的给定角度返回三角函数比值。
a=np.array([0,30,45,60,90])
print('不同角度的正弦值')
#通过成pi/180 转化为弧度
print(np.sin(a*np.pi/180))
print('\n')
print('数组中角度的余弦值')
print(np.cos(a*np.pi/180))
print('\n')
print('数组中角度的正弦值')
print(np.tan(a*np.pi/180))

不同角度的正弦值
[ 0.          0.5         0.70710678  0.8660254   1.        ]


数组中角度的余弦值
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


数组中角度的正弦值
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]


In [41]:
# arcsin，arccos，和arctan函数返回给定角度的sin，cos和tan的反三角函数。 
# 这些函数的结果可以通过numpy.degrees()函数通过将弧度制转换为角度制来验证。
a=np.array([0,30,45,90])
print('含有正弦值的数组')
sin=np.sin(a*np.pi/180)
print(sin)
print('\n')
print('计算角度的反正弦，返回值以弧度为单位')
inv=np.arcsin(sin)
print(inv)
print('\n')
print('通过转化为角度制来检查结果')
print(np.degrees(inv))
print('\n')
print('arccos 和arctan 函数行为类似')
cos=np.cos(a*np.pi/180)
print(cos)
print('\n')
print('反余弦')
inv=np.arccos(cos)
print(inv)
print('\n')

print('角度制单位')
print(np.degrees(inv))
print('\n')
print('tan函数')
tan=np.tan(a*np.pi/180)
print(tan)


含有正弦值的数组
[ 0.          0.5         0.70710678  1.        ]


计算角度的反正弦，返回值以护肚围单位
[ 0.          0.52359878  0.78539816  1.57079633]


通过转化为角度制来检查结果
[  0.  30.  45.  90.]


arccos 和arctan 函数行为类似
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   6.12323400e-17]


反余弦
[ 0.          0.52359878  0.78539816  1.57079633]


角度制单位
[  0.  30.  45.  90.]


tan函数
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.63312394e+16]


In [42]:
# numpy.around()
# 这个函数返回四舍五入到所需精度的值。 该函数接受以下参数。
a=np.array([1,5.55,123,0.567,25,532])
print('原数组')
print(a)
print('\n')
print('舍入后')
print(np.around(a))
print(np.around(a,decimals=1))
print(np.around(a,decimals=-1))


原数组
[   1.       5.55   123.       0.567   25.     532.   ]


舍入后
[   1.    6.  123.    1.   25.  532.]
[   1.     5.6  123.     0.6   25.   532. ]
[   0.   10.  120.    0.   20.  530.]


In [43]:
# numpy.floor()
# 此函数返回不大于输入参数的最大整数。 即标量x 的下限是最大的整数i ，使得i <= x。 注意在Python中，向下取整总是从 0 舍入。
a=np.array([-1.7,1.5,-0.2,0.6,10])
print('提供的数组')
print(a)
print('\n')
print('修改后的数组')
print(np.floor(a))

提供的数组
[ -1.7   1.5  -0.2   0.6  10. ]


修改后的数组
[ -2.   1.  -1.   0.  10.]


In [44]:
# numpy.ceil()
# ceil()函数返回输入值的上限，即，标量x的上限是最小的整数i ，使得i> = x。
a=np.array([-1.7,1.5,-0.2,0.6,10])
print('提供的数组')
print(a)
print('\n')
print('修改后的数组')
print(np.ceil(a))

提供的数组
[ -1.7   1.5  -0.2   0.6  10. ]


修改后的数组
[ -1.   2.  -0.   1.  10.]


In [46]:
# NumPy - 算数运算
# 用于执行算术运算(如add()，subtract()，multiply()和divide())的输入数组必须具有相同的形状或符合数组广播规则。
a=np.arange(9,dtype=np.float_).reshape(3,3)
print('第一个数组')
print(a)
print('\n')
print('第二个数组')
b=np.array([10,10,10])
print(b)
print('\n')
print('两个数组相加')
print(np.add(a,b))
print('\n')
print('两个数组相减')
print(np.subtract(a,b))
print('\n')
print('两个数组相乘')
print(np.multiply(a,b))
print('\n')
print('两个数组相除')
print(np.divide(a,b))

第一个数组
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


第二个数组
[10 10 10]


两个数组相加
[[ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]]


两个数组相减
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


两个数组相乘
[[  0.  10.  20.]
 [ 30.  40.  50.]
 [ 60.  70.  80.]]


两个数组相除
[[ 0.   0.1  0.2]
 [ 0.3  0.4  0.5]
 [ 0.6  0.7  0.8]]


In [47]:
# numpy.reciprocal()
# 函数返回参数逐元素的倒数，。 由于 Python 处理整数除法的方式，对于绝对值大于 1 的整数元素，结果始终为 0， 对于整数 0，则发出溢出警告。
a=np.array([0.25,1.33,1,0,100])
print('我们的数组是')
print(a)
print('\n')
print('调用reciprocal函数')
print(np.reciprocal(a))
print('\n')

b=np.array([100],dtype=int)
print('第二个数组')
print(b)
print('\n')
print('调用reciprocal函数')
print(np.reciprocal(b))

我们的数组是
[   0.25    1.33    1.      0.    100.  ]


调用reciprocal函数
[ 4.         0.7518797  1.               inf  0.01     ]


第二个数组
[100]


调用reciprocal函数
[0]


d:\python3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in reciprocal
  


In [49]:
# numpy.power()
# 此函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。
a=np.array([10,100,1000])
print('我们的数组是：')
print(a)
print('\n')
print('调用power函数')
print(np.power(a,2))
print('\n')
print('第二个数组')
b=np.array([1,2,3])
print(b)
print('\n')
print('再次调用power函数')
print(np.power(a,numpy.mod()

此函数返回输入数组中相应元素的除法余数。 函数numpy.remainder()也产生相同的结果。

b))

我们的数组是：
[  10  100 1000]


调用power函数
[    100   10000 1000000]


第二个数组
[1 2 3]


再次调用power函数
[        10      10000 1000000000]


In [50]:
# numpy.mod()
# 此函数返回输入数组中相应元素的除法余数。 函数numpy.remainder()也产生相同的结果。
a=np.array([10,20,30])
b=np.array([3,5,7])
print('第一个数组是')
print(a)
print('\n')
print(b)
print('\n')
print('调用mod()函数')
print(np.mod(a,b))
print('\n')
print('调用remainder()函数')
print(np.remainder(a,b))


第一个数组是
[10 20 30]


[3 5 7]


调用mod()函数
[1 0 2]


调用remainder()函数
[1 0 2]


In [52]:
# 以下函数用于对含有复数的数组执行操作。
# numpy.real() 返回复数类型参数的实部。
# numpy.imag() 返回复数类型参数的虚部。
# numpy.conj() 返回通过改变虚部的符号而获得的共轭复数。
# numpy.angle() 返回复数参数的角度。 函数的参数是degree。 如果为true，返回的角度以角度制来表示，否则为以弧度制来表示。
a=np.array([-5.6j,0.2j,11,1+1j])
print('我们的数组是：')
print(a)
print('\n')
print('调用real()函数')
print(np.real(a))
print('\n')

print('调用imag()函数')
print(np.imag(a))
print('\n')

print('调用conj()函数')
print(np.conj(a))
print('\n')

print('调用angle()函数')
print(np.angle(a))
print('\n')

print('再次调用angle()函数（以角度制返回）')
print(np.angle(a,deg=True))

我们的数组是：
[ -0.-5.6j   0.+0.2j  11.+0.j    1.+1.j ]


调用real()函数
[ -0.   0.  11.   1.]


调用imag()函数
[-5.6  0.2  0.   1. ]


调用conj()函数
[ -0.+5.6j   0.-0.2j  11.-0.j    1.-1.j ]


调用angle()函数
[-1.57079633  1.57079633  0.          0.78539816]


再次调用angle()函数（以角度制返回）
[-90.  90.   0.  45.]


In [54]:
# numpy.amin() 和 numpy.amax()
# 这些函数从给定数组中的元素沿指定轴返回最小值和最大值。
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
print('我们的数组是')
print(a)
print('\n')

print('调用amin()函数')
print(np.amin(a,1))
print('再次调用amin()函数')
print(np.amin(a,0))
print('\n')

print('调用amax()函数')
print(np.amax(a))
print('再次调用amax()函数')
print(np.amax(a,axis=0))

我们的数组是
[[3 7 5]
 [8 4 3]
 [2 4 9]]


调用amin()函数
[3 3 2]
再次调用amin()函数
[2 4 3]


调用amax()函数
9
再次调用amax()函数
[8 7 9]


In [56]:
# numpy.ptp()
# numpy.ptp()函数返回沿轴的值的范围(最大值 - 最小值)。
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
print('我们的数组是')
print(a)
print('\n')

print('调用ptp()函数')
print(np.ptp(a))
print('\n')
print('沿轴1调用ptp()函数')
print(np.ptp(a,axis=1))
print('\n')

print('沿 轴0调用ptp()函数')
print(np.ptp(a,axis=0))
      

我们的数组是
[[3 7 5]
 [8 4 3]
 [2 4 9]]


调用ptp()函数
7


沿轴1调用ptp()函数
[4 5 7]


沿 轴0调用ptp()函数
[6 3 6]


In [58]:
# numpy.percentile()
# 百分位数是统计中使用的度量，表示小于这个值得观察值占某个百分比。 函数numpy.percentile()接受以下参数。
# numpy.percentile(a, q, axis)
# Python
# 其中：
# 序号	参数及描述
# 1.	a 输入数组
# 2.	q 要计算的百分位数，在 0 ~ 100 之间
# 3.	axis 沿着它计算百分位数的轴

a=np.array([[30,40,70],[80,20,10],[0,90,60]])
print('我们的数组是')
print(a)
print('\n')
print('调用percentile()函数')
print(np.percentile(a,50))
print('\n')
print('沿轴1调用percentile()函数')
print(np.percentile(a,50,axis=1))
print('\n')

print('沿轴0调用percentile()函数')
print(np.percentile(a,50,axis=0))

我们的数组是
[[30 40 70]
 [80 20 10]
 [ 0 90 60]]


调用percentile()函数
40.0


沿轴1调用percentile()函数
[ 40.  20.  60.]


沿轴0调用percentile()函数
[ 30.  40.  60.]


In [59]:
# numpy.median()
# 中值定义为将数据样本的上半部分与下半部分分开的值。 numpy.median()函数的用法如下面的程序所示。
a=np.array([[30,65,70],[80,95,10],[50,90,60]])
print('我们的数组是')
print(a)
print('\n')
print('调用median()函数')
print(np.median(a))
print('\n')

print('沿轴0调用median()函数')
print(np.median(a,axis=0))
print('\n')

print('沿轴1调用median()函数')
print(np.mean(a,axis=1))

我们的数组是
[[30 65 70]
 [80 95 10]
 [50 90 60]]


调用median()函数
65.0


沿轴0调用median()函数
[ 50.  90.  60.]


沿轴1调用median()函数
[ 55.          61.66666667  66.66666667]


In [60]:
# numpy.mean()
# 算术平均值是沿轴的元素的总和除以元素的数量。 numpy.mean()函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('我们的数组是')
print(a)
print('\n')
print('调用mean()函数')
print(np.mean(a))
print('\n')
print('沿轴0调用mean()函数')
print(np.mean(a,axis=0))
print('\n')

print('沿轴1调用mean()函数')
print(np.mean(a,axis=1))

我们的数组是
[[1 2 3]
 [4 5 6]
 [7 8 9]]


调用mean()函数
5.0


沿轴0调用mean()函数
[ 4.  5.  6.]


沿轴1调用mean()函数
[ 2.  5.  8.]


In [63]:
# numpy.average()
# 加权平均值是由每个分量乘以反映其重要性的因子得到的平均值。 numpy.average()函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。 该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。
# 考虑数组[1,2,3,4]和相应的权重[4,3,2,1]，通过将相应元素的乘积相加，并将和除以权重的和，来计算加权平均值。
# 加权平均值 = (1*4+2*3+3*2+4*1)/(4+3+2+1)
a=np.array([1,2,3,4])
print('我们的数组是')
print(a)
print('\n')
print('调用avergae函数')
print(np.average(a))
print('\n')
#不指定权重时相当于average()函数
wts=np.array([4,3,2,1])
print('再次调用average()函数')
print(np.average(a,weights=wts))
print('\n')
#如果returned参数设为ture,则返回权重的和
print('权重的和')
print(np.average([1,2,3,4],weights=[4,3,2,1]))

# 在多维数组中，可以指定用于计算的轴。
a=np.arange(6).reshape(3,2)
print('我们的数组是')
print(a)
print('\n')

print('修改后的数组')
wt=np.array([3,5])
print(np.average(a,axis=1,weights=wt))
print('\n')
print('修改后的数组')
print(np.average(a,axis=1,weights=wt,returned=True))

我们的数组是
[1 2 3 4]


调用avergae函数
2.5


再次调用average()函数
2.0


权重的和
2.0
我们的数组是
[[0 1]
 [2 3]
 [4 5]]


修改后的数组
[ 0.625  2.625  4.625]


修改后的数组
(array([ 0.625,  2.625,  4.625]), array([ 8.,  8.,  8.]))


In [65]:
# 标准差
# 标准差是与均值的偏差的平方的平均值的平方根。 标准差公式如下：
# std = sqrt(mean((x - x.mean())**2))
# Python
# 如果数组是[1，2，3，4]，则其平均值为2.5。 因此，差的平方是[2.25,0.25,0.25,2.25]，并且其平均值的平方根除以4，即sqrt(5/4)是1.1180339887498949。
print(np.std([1,2,3,4]))

1.11803398875


In [66]:
# 方差
# 方差是偏差的平方的平均值，即mean((x - x.mean())** 2)。 换句话说，标准差是方差的平方根。
print(np.var([1,2,3,4]))


1.25


In [69]:
# NumPy中提供了各种排序相关功能。 这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度，最坏情况性能，所需的工作空间和算法的稳定性。 下表显示了三种排序算法的比较。
# 种类	速度	最坏情况	工作空间	稳定性
# 'quicksort'(快速排序)	1	O(n^2)	0	否
# 'mergesort'(归并排序)	2	O(n*log(n))	~n/2	是
# 'heapsort'(堆排序)	3	O(n*log(n))	0	否
# numpy.sort()
# sort()函数返回输入数组的排序副本。 它有以下参数：
# numpy.sort(a, axis, kind, order)
# Python
# 其中：
# 序号	参数及描述
# 1.	a 要排序的数组
# 2.	axis 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序
# 3.	kind 默认为'quicksort'(快速排序)
# 4.	order 如果数组包含字段，则是要排序的字段
a=np.array([[3,7],[9,1]])
print('我们的数组是')
print(a)
print('\n')
print('调用sort()函数')
print(np.sort(a))
print('\n')
print('沿轴0排序')
print(np.sort(a,axis=0))
print('\n')

#在sort函数中排序字段
dt=np.dtype([('name','S10'),('age','int')])
a=np.array([('li',18),('zhao',19),('qian',20),('sun',32)],dtype=dt)
print('我们的数组是')
print(a)
print('\n')

print('按name排序')
print(np.sort(a,order='name'))

我们的数组是
[[3 7]
 [9 1]]


调用sort()函数
[[3 7]
 [1 9]]


沿轴0排序
[[3 1]
 [9 7]]


我们的数组是
[(b'li', 18) (b'zhao', 19) (b'qian', 20) (b'sun', 32)]


按name排序
[(b'li', 18) (b'qian', 20) (b'sun', 32) (b'zhao', 19)]


In [71]:
# numpy.argsort()
# numpy.argsort()函数对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。 这个索引数组用于构造排序后的数组。
x=np.array([3,1,2])
print('我们的数组是')
print(x)
print('\n')
print('对x 调用 argsort()函数')
y=np.argsort(x)
print(y)
print('\n')
print('以排序后的顺序重构原数组')
print(x[y])
print('\n')
print('使用循环重构原数组')
for i in y:
    print (x[i])

我们的数组是
[3 1 2]


对x 调用 argsort()函数
[1 2 0]


以排序后的顺序重构原数组
[1 2 3]


使用循环重构原数组
1
2
3


In [72]:
# numpy.lexsort()
# 函数使用键序列执行间接排序。 键可以看作是电子表格中的一列。 该函数返回一个索引数组，使用它可以获得排序数据。 注意，最后一个键恰好是 sort 的主键。
nm=('zhao','qian','sun','li')
dv=('f.y','s.y','s.y','f.y')
ind=np.lexsort((dv,nm))
print('调用lexsort()函数')
print(ind)
print('\n')
print('使用这个索引来获取排序后的数据')
print([nm[i]+','+dv[i] for i in ind])

调用lexsort()函数
[3 1 2 0]


使用这个索引来获取排序后的数据
['li,f.y', 'qian,s.y', 'sun,s.y', 'zhao,f.y']


In [77]:
# numpy.argmax() 和 numpy.argmin()
# 这两个函数分别沿给定轴返回最大和最小元素的索引。
a=np.array([[30,40,70],[80,20,10],[50,90,60]])
print('我们的数组是')
print(a)
print('\n')
print('调用argmax()函数')
print(np.argmax(a))
print('\n')

print('展开数组')
print(a.flatten())
print('\n')

print('沿轴0 的最大索引')
maxindex=np.argmax(a,axis=0)
print(maxindex)
print('\n')

print('沿轴1的最大索引')
maxindex=np.argmax(a,axis=1)
print(maxindex)
print('\n')

print('调用argmin()函数')
minindex=np.argmin(a)
print(minindex)
print('\n')

print('展开数组中的最小值')
print(a.flatten()[minindex])
print('\n')
print('沿轴0的最小值索引')
minindex=np.argmin(a,axis=0)
print(minindex)
print('\n')

print('沿轴1的最小值的索引')
minindex=np.argmin(a,axis=1)
print(minindex)

我们的数组是
[[30 40 70]
 [80 20 10]
 [50 90 60]]


调用argmax()函数
7


展开数组
[30 40 70 80 20 10 50 90 60]


沿轴0 的最大索引
[1 2 0]


沿轴1的最大索引
[2 0 1]


调用argmin()函数
5


展开数组中的最小值
10


沿轴0的最小值索引
[0 1 1]


沿轴1的最小值的索引
[0 2 0]


In [79]:
# numpy.nonzero()
# numpy.nonzero()函数返回输入数组中非零元素的索引。
a=np.array([[30,40,0],[0,20,10],[50,0,60]])
print('我们的数组是')
print(a)
print('\n')

print('调用nonozero()函数')
print(np.nonzero(a))

我们的数组是
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]


调用nonozero()函数
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


In [81]:
# numpy.where()
# where()函数返回输入数组中满足给定条件的元素的索引。
x=np.arange(9).reshape(3,3)
print('我们的数组是')
print(x)

print('大于3的元素的索引')
y=np.where(x>3)
print(y)
print('使用这些索引来获取满足条件的元素')
print(x[y])

我们的数组是
[[0 1 2]
 [3 4 5]
 [6 7 8]]
大于3的元素的索引
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
使用这些索引来获取满足条件的元素
[4 5 6 7 8]


In [82]:
# numpy.extract()
# extract()函数返回满足任何条件的元素。

x=np.arange(9).reshape(3,3)
print('我们的数组')
print(x)
#定义条件
condition=np.mod(x,2) ==0
print('按元素的条件值')
print(condition)
print('使用条件提取元素')
print(np.extract(condition,x))

我们的数组
[[0 1 2]
 [3 4 5]
 [6 7 8]]
按元素的条件值
[[ True False  True]
 [False  True False]
 [ True False  True]]
使用条件提取元素
[0 2 4 6 8]


In [86]:
# numpy.ndarray.byteswap()
# numpy.ndarray.byteswap()函数在两个表示：大端和小端之间切换。
a=np.array([1,256,8755],dtype=np.int16)
print('我们的数组是')
print(a)
print('以十六进制表示内存中的数据')
print(map(hex,a))
#byswap()函数通过传入true来源原地交换

print('调用byswap()函数')
print(b.byteswap(True))
print('十六进制形式')
print(map(hex,a))
#我们可以看到字节已经交换了

我们的数组是
[   1  256 8755]
以十六进制表示内存中的数据
调用byswap()函数
[ 50331648  83886080 117440512]
十六进制形式
