In [1]:
import numpy as np

In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr2=np.array([[1,1,2],[2,3,3]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]


In [6]:
print(arr1+arr2)#两个矩阵相加

[[2 3 5]
 [6 8 9]]


In [7]:
print(arr1-arr2)#两个矩阵相减

[[0 1 1]
 [2 2 3]]


In [8]:
print(arr1*arr2)#两个矩阵的元素的乘积

[[ 1  2  6]
 [ 8 15 18]]


In [9]:
print(arr1**arr2)#arr1的元素的指数是arr2的元素

[[  1   2   9]
 [ 16 125 216]]


In [10]:
print(arr1/arr2)#矩阵的元素相除

[[ 1.          2.          1.5       ]
 [ 2.          1.66666667  2.        ]]


In [11]:
print(arr1%arr2)#取余

[[0 0 1]
 [0 2 0]]


In [12]:
print(arr1//arr2)#取整的操作

[[1 2 1]
 [2 1 2]]


In [13]:
print(arr1+2)#矩阵所有的元素+2

[[3 4 5]
 [6 7 8]]


In [14]:
print(arr1*10)#矩阵所有的元素 X 10

[[10 20 30]
 [40 50 60]]


In [17]:
arr3=arr1>3#判断arr1中 大于3或者小于3的元素
print(arr3)

[[False False False]
 [ True  True  True]]


In [18]:
arr4=np.ones((3,5))
print(arr4)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [19]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [21]:
np.dot(arr1,arr4)#矩阵的乘法

array([[  6.,   6.,   6.,   6.,   6.],
       [ 15.,  15.,  15.,  15.,  15.]])

In [23]:
print(arr1)
print(arr1.T)
print(np.transpose(arr1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [35]:
n = 3
res = [[0] * n] * n
print(res)
print(id(res[0][0]),id(res[1][0]),id(res[0][1]))
k = 1
for i in range(n):    
    for j in range(n):
        res[i][j] = k
        k += 1
print(res)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
491351488 491351488 491351488
[[7, 8, 9], [7, 8, 9], [7, 8, 9]]


In [97]:
str='''V. CONCLUSIONS
This paper presents an s-FCN-loc model based on VGGnet for road detection which is able to learn discriminative
features of road boundaries to detect more accurate road
regions by exploiting the RGB-channel image, semantic
contour and location prior simultaneously. Stepwise experimental results verify the effectiveness of each component in
the proposed method. We also find that s-FCN-loc converges
faster than the original FCN at the training stage, which saves
more training time. In the future, we plan to transform the
siamesed architecture to other neural network and explore the
changes of conv layers brought by adding contour stream
through visualization operation, which will prompt us to
understand the effects of contour map in depth.'''
print(str.replace('\n',''))

V. CONCLUSIONSThis paper presents an s-FCN-loc model based on VGGnet for road detection which is able to learn discriminativefeatures of road boundaries to detect more accurate roadregions by exploiting the RGB-channel image, semanticcontour and location prior simultaneously. Stepwise experimental results verify the effectiveness of each component inthe proposed method. We also find that s-FCN-loc convergesfaster than the original FCN at the training stage, which savesmore training time. In the future, we plan to transform thesiamesed architecture to other neural network and explore thechanges of conv layers brought by adding contour streamthrough visualization operation, which will prompt us tounderstand the effects of contour map in depth.


In [ ]:
Towards End-to-End Lane Detection an Instance Segmentation Approach