In [2]:
import numpy as np
a=np.array([1,2,3])
print (a)

[1 2 3]


In [10]:
#多于一个维度
b=np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [16]:
#最小维度
c=np.array([1,2,3,4,5],ndmin=2)
print (c)

[[1 2 3 4 5]]


In [17]:
#dtype参数
d=np.array([1,2,3],dtype=complex)
print (d)

[ 1.+0.j  2.+0.j  3.+0.j]


In [18]:
#使用数组标量类型
dt=np.dtype(np.int32)
print(dt)

int32


In [20]:
dt=np.dtype('i4')
print (dt)

int32


In [28]:
#使用端记号
dt=np.dtype('>i4')
print (dt)

#构建结构化数据类型
dt=np.dtype([('age',np.int8)])
print (dt)

#现在将其应用于ndarray对象
aa=np.array([(10,),(20,),(30,)],dtype=dt)
print (aa)

#文件名称可用于访问age列的内容
print (aa['age'])


#以下示例定义名为 student 的结构化数据类型，
#其中包含字符串字段name，整数字段age和浮点字段marks。
#此dtype应用于ndarray对象。
student=np.dtype([('name','S20'),('age','i1'),('mark','f4')])
list_tup=np.array([('abc',21,50),('xy',18,75)],dtype=student)
print (list_tup)


>i4
[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]
[(b'abc', 21,  50.) (b'xy', 18,  75.)]


In [24]:
# class A:
#     def __init__(self):
#         self.a = [99999999 ** 10] * 50
        
# d = []
# for i in range(2000000):
#     d.append(A())
    
# d = None

In [39]:
# ndarray.shape
# 这一数组属性返回一个包含数组维度的元组，它也可以用于调整数组大小。
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

# 这会调整数组大小 
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print (a)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [40]:
#NumPy 也提供了reshape函数来调整数组大小。
a=np.array([[1.,2,3],[4,5,6]])
b=a.reshape(3,2)
print (b)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [42]:
# ndarray.ndim
# 这一数组属性返回数组的维数。
#等间隔数字的数组
a=np.arange(24)
print (a)

#一维数组
a=np.arange(24)
a.ndim
print(a.ndim)
#现在调整其大小
b=a.reshape(2,4,3)
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [46]:
# umpy.itemsize
# 这一数组属性返回数组中每个元素的字节单位长度。
#数组的dtype为int8(一个字节)
x=np.array([1,2,3,4,5],dtype=np.int8)
print (x.itemsize)

#数组的dtype现在为float32(四个字节)
x=np.array([1,2,3,4,5],dtype=np.float32)
print (x.itemsize)

1
4


In [47]:
# numpy.flags
x=np.array([1,2,3,4])
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [48]:
# numpy.empty
# 它创建指定形状和dtype的未初始化数组。 它使用以下构造函数：
x=np.empty([3,2], dtype=int)
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
#含有5个0的数组，默认类型为float
x=np.zeros(5)
print (x)

[ 0.  0.  0.  0.  0.]


In [50]:
#将其改为int类型
x=np.zeros((5,),dtype=np.int)
print (x)

[0 0 0 0 0]


In [52]:
#自定义类型
x=np.zeros((2,2,),dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [53]:
#将列表转换为ndarray
x=[1,2,3]
a=np.asarray(x)
print (a)

[1 2 3]


In [54]:
#设置了dtype
x=[1,2,3]
a=np.asarray(x,dtype=float)
print (a)

[ 1.  2.  3.]


In [55]:
#来自元组的ndarray
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [56]:
#来自元组列表的ndarray
x=[(1,2,3),(4,5)]
a=np.asarray(x)
print (a)

[(1, 2, 3) (4, 5)]


In [61]:
# numpy.frombuffer
# 此函数将缓冲区解释为一维数组。 暴露缓冲区接口的任何对象都用作参数来返回ndarray
s="Helloworld".encode('ascii')#首先要经过编码
a=np.frombuffer(s,dtype='S1')
print (a)

[b'H' b'e' b'l' b'l' b'o' b'w' b'o' b'r' b'l' b'd']


In [66]:
#使用ranage函数创建列表对象  果然没有显示列表值，只有iter创建才可以
list=range(5)
print (list)

range(0, 5)


In [67]:
#从列表中获得迭代器
list=range(5)
it=iter(list)#使用迭代器创建ndarray  
x=np.fromiter(it,dtype=float)
print (x)

[ 0.  1.  2.  3.  4.]


In [70]:
# numpy.arange
# 这个函数返回ndarray对象，包含给定范围内的等间隔值。
x=np.arange(5)
print (x)

[0 1 2 3 4]


In [71]:
#设置了dtype
x=np.arange(5,dtype=float)
print(x)

[ 0.  1.  2.  3.  4.]


In [72]:
#设置了起始值和终止值的参数
x=np.arange(10,20,2)
print (x)

[10 12 14 16 18]


In [73]:
# numpy.linspace
# 此函数类似于arange()函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长。 此函数的用法如下。
x=np.linspace(10,50,5)
print (x)


[ 10.  20.  30.  40.  50.]


In [74]:
x=np.linspace(10,20,5)
print (x)
#将endpoint设为false
x=np.linspace(10,20,5,endpoint=False)#这是按整数划分
print (x)

[ 10.  12.  14.  16.  18.]


In [77]:
#输出retstep的值
x=np.linspace(1,2,5,retstep=True)#显示每个间隔之间的间隔值
print (x)

(array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ]), 0.25)


In [79]:
# numpy.logspace
# 此函数返回一个ndarray对象，其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。
#默认底数是10
a=np.logspace(1.0,2.0,num=10)
print (a)

[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [80]:
#将对数空间的底数设置为2
a=np.logspace(1,10,num=10,base=2)
print (a)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


In [82]:
# 基本切片是 Python 中基本切片概念到 n 维的扩展。 
# 通过将start，stop和step参数提供给内置的slice函数来构造一个 Python slice对象。 此slice对象被传递给数组来提取数组的一部分。
a=np.arange(10)
s=slice(2,7,2)
print (a)
print(s)
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]


In [83]:
a=np.arange(10)
b=a[2:7:2]
print (b)

[2 4 6]


In [85]:
#对单个元素进行切片
a=np.arange(10)
print( a[2])

[2 3 4 5 6 7 8 9]


In [91]:
#对食欲索引的元素进行切片
a=np.arange(10)
print (a[3:])
print (a[2:5])

[3 4 5 6 7 8 9]
[2 3 4]


In [95]:
#对索引之间的元素进行切片
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (a)
#对于始于索引的元素进行切片
print ('现在我们从索引a[1:]开始对数组进行切片')
print (a[0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
现在我们从索引a[1:]开始对数组进行切片
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
# 切片还可以包括省略号(...)，
# 来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的ndarray。

#最开始的数组
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('我们的数组是：')
print (a)
print('\n')
#这会返回第二列的数组
print('第二列的元素是：')
print (a[...,1])
print('第二行的元素是：')
print (a[1,...])
print ('\n')
#现在我们从第二列向后切片所有的元素：
print ('第二列及其剩余的元素是：')
print (a[...,1:])


我们的数组是：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


第二列的元素是：
[2 5 8]
第二行的元素是：
[4 5 6]


第二列及其剩余的元素是：
[[2 3]
 [5 6]
 [8 9]]


In [106]:
# 整数索引
# 这种机制有助于基于 N 维索引来获取数组中任意元素。 每个整数数组表示该维度的下标值。 当索引的元素个数就是目标ndarray的维度时，会变得相当直接。
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
y=x[[0,1,2],[0,1,0]]
print (y)

[0 4 6]


In [113]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('我们的数组是：')
print (x)
print('\n')
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]
print(rows)
print (cols)
print (y)
print ('这个数组的每个角元素的元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]
这个数组的每个角元素的元素是：
[[ 0  2]
 [ 9 11]]


In [115]:
# 高级和基本索引可以通过使用切片:或省略号...与索引数组组合。
# 以下示例使用slice作为列索引和高级索引。 当切片用于两者时，结果是相同的。 但高级索引会导致复制，并且可能有不同的内存布局。
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print ('我们的数组是：')
print (x)
print ('\n')
#切片
z=x[1:4,1:3]
print('切片后，我们的数组变为：')
print (z)
print ('\n')
#对列使用高级索引
y=x[1:4,[1,2]]
print ('对列使用高级索引来切片：')
print (y)

我们的数组是：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


切片后，我们的数组变为：
[[ 5  6]
 [ 8  9]
 [11 12]]


对列使用高级索引来切片：
[[ 5  6]
 [ 8  9]
 [11 12]]


In [116]:
# 当结果对象是布尔运算(例如比较运算符)的结果时，将使用此类型的高级索引。
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print ('我们的数组是：')
print (x)
print ('\n')
#现在我们会打印出大于5的元素
print('大于5的元素是：')
print(x[x>5])





我们的数组是：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


大于5的元素是：
[ 6  7  8  9 10 11 12]


In [120]:
# 这个例子使用了~(取补运算符)来过滤NaN
a=np.array([np.nan,1,2,np.nan,3,4,5])
print (a[~np.isnan(a)])#过滤掉NAN

[ 1.  2.  3.  4.  5.]


In [125]:
# 以下示例显示如何从数组中过滤掉非复数元素。
a=np.array([1,2+6j,5,3.5+5j])
print (a[np.iscomplex(a)])#获取复数

[ 1.+0.j  5.+0.j]


In [126]:
# NumPy - 广播
# 术语广播是指 NumPy 在算术运算期间处理不同形状的数组的能力。
# 对数组的算术运算通常在相应的元素上进行。 如果两个阵列具有完全相同的形状，则这些操作被无缝执行。
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
c=a*b
print (c)

[ 10  40  90 160]


In [127]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])
print ('第一个数组')
print (a)
print ('\n')
print('第二个数组：')
print (b)
print ('\n')
print('第一个数组加上第二个数组：')
print(a+b)

第一个数组
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]


第二个数组：
[ 1.  2.  3.]


第一个数组加上第二个数组：
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [128]:
# NumPy - 数组上的迭代
# NumPy 包包含一个迭代器对象numpy.nditer。 它是一个有效的多维迭代器对象，可以用于在数组上进行迭代。
# 数组的每个元素可使用 Python 的标准Iterator接口来访问。
# 让我们使用arange()函数创建一个 3X4 数组，并使用nditer对它进行迭代。
a=np.arange(0,60,5)
a=a.reshape(3,4)
print ("原始数组第：")
print (a)
print ('\n')
print('修改后的数组是')
for x in np.nditer(a):
    print(x)

原始数组第：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是
0
5
10
15
20
25
30
35
40
45
50
55


In [129]:
# 迭代的顺序匹配数组的内容布局，而不考虑特定的排序。 这可以通过迭代上述数组的转置来看到
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('原始数组是：')
print(a)
print('\n')
print('原始数组的转置是')
b=a.T
print(b)
print('\n')

print('修改后的数组是：')
for x in np.nditer(b):
    print(x)

      

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


修改后的数组是：
0
5
10
15
20
25
30
35
40
45
50
55


In [132]:
# 迭代顺序
# 如果相同元素使用 F 风格顺序存储，则迭代器选择以更有效的方式对数组进行迭代。
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('原始数组是：')
print (a)
print('\n')
print('原始数组的转置是：')
b=a.T
print(b)
print('\n')
print('以C风格顺序排序：')
c=b.copy(order='C')
print(c )
for x in np.nditer(c):
    print(x)
print('\n')
print('以F风格顺序排序：')
c=b.copy(order='F')
print(c)
for x in np.nditer(c):
    print(x)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以C风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


以F风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [133]:
# 修改数组的值
# nditer对象有另一个可选参数op_flags。 其默认值为只读，
# 但可以设置为读写或只写模式。 这将允许使用此迭代器修改数组元素。
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('原始数组是：')
print(a)
print('\n')
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
print('修改后的数组是：')
print (a)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [134]:
# 在下面的示例中，迭代器遍历对应于每列的一维数组。
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('原始数组是：')
print(a)
print('\n')
print('修改后的数组是：')
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [139]:
# 广播迭代
# 如果两个数组是可广播的，nditer组合对象能够同时迭代它们。 
# 假设数组a具有维度 3X4，并且存在维度为 1X4 的另一个数组b，则使用以下类型的迭代器(数组b被广播到a的大小)。
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('第一个数组是 ;')
print(a)
print('\n')
print('第二个数组是：')
b=np.array([1,2,3,4],dtype=int)
print (b)
print('\n')
print('修改后的数组是：')
for x,y in np.nditer([a,b]):
    print(x,y)

第一个数组是 ;
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组是：
[1 2 3 4]


修改后的数组是：
0 1
5 2
10 3
15 4
20 1
25 2
30 3
35 4
40 1
45 2
50 3
55 4


In [140]:
a=np.arange(8)
print ('原始数组')
print(a)
print('\n')
b=a.reshape(4,2)
print('修改后的数组：')
print(b)


原始数组
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [142]:
a=np.arange(8).reshape(2,4)
print('原始数组')
print(a)
print('\n')

print('调用flat函数之后')
#返回展开数组中的下标的对应的元素
print(a.flat[5])

原始数组
[[0 1 2 3]
 [4 5 6 7]]


调用flat函数之后
5


In [144]:
# numpy.ndarray.flatten
# 该函数返回折叠为一维的数组副本，函数接受下列参数：
# ndarray.flatten(order)
a = np.arange(8).reshape(2,4)
print ('原数组：')
print (a)
print ('\n')
print('展开的数组：')
print(a.flatten())
print('\n')
print('以F风格顺序展开的数组')
print(a.flatten(order='F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以F风格顺序展开的数组
[0 4 1 5 2 6 3 7]


In [146]:
# numpy.ravel
# 这个函数返回展开的一维数组，并且按需生成副本。
# 返回的数组和输入数组拥有相同数据类型。这个函数接受两个参数。
a=np.arange(8).reshape(2,4)
print('原数组：')
print(a)
print('\n')
print('调用ravel函数之后：')
print(a.ravel(order='F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用ravel函数之后：
[0 1 2 3 4 5 6 7]


In [147]:
# numpy.transpose
# 这个函数翻转给定数组的维度。如果可能的话它会返回一个视图。函数接受下列参数：
# numpy.transpose(arr, axes)
a=np.arange(12).reshape(3,4)
print('原数组：')
print(a)
print('\n')
print('转置数组：')
print(np.transpose(a))


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [148]:
# numpy.ndarray.T
# 该函数属于ndarray类，行为类似于numpy.transpose。
a=np.arange(12).reshape(3,4)
print('原数组：')
print(a)
print('\n')
print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [151]:
# numpy.rollaxis
# 该函数向后滚动特定的轴，直到一个特定位置。这个函数接受三个参数：
# numpy.rollaxis(arr, axis, start)
# 其中：
# arr：输入数组
# axis：要向后滚动的轴，其它轴的相对位置不会改变
# start：默认为零，表示完整的滚动。会滚动到特定位置。
a=np.arange(8).reshape(2,2,2)
print('原数组：')
print(a)
print('\n')

#将轴滚动到轴0（宽度到深度）
print('调用rollaaxis函数')
print(np.rollaxis(a,2))
#将轴0滚动到轴1（宽度到高度）
print('\n')
print('调用rollaxis函数')
print(np.rollaxis(a,2,1))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用rollaaxis函数
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


调用rollaxis函数
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [152]:
# numpy.swapaxes
# 该函数交换数组的两个轴。对于 1.10 之前的 NumPy 版本，会返回交换后数组的试图。这个函数接受下列参数：
# numpy.swapaxes(arr, axis1, axis2)
# arr：要交换其轴的输入数组
# axis1：对应第一个轴的整数
# axis2：对应第二个轴的整数
a=np.arange(8).reshape(2,2,2)
print('原数组;')
print(a)
print('\n')
#现在交换轴0(深度方向)到轴2（宽度方向）
print('调用swapaxes 函数后的数组：')
print(np.swapaxes(a,2,0))

原数组;
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用swapaxes 函数后的数组：
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [159]:
# broadcast
# 如前所述，NumPy 已经内置了对广播的支持。 此功能模仿广播机制。 它返回一个对象，该对象封装了将一个数组广播到另一个数组的结果。
# 该函数使用两个数组作为输入参数。 下面的例子说明了它的用法。

x=np.array([[1],[2],[3]])
y=np.array([4,5,6])

#对y广播x
b=np.broadcast(x,y)
#它使用iterator属性，基于自身组件的迭代器元组
r,c=b.iters
print(r)
print(c)
# print(r.next(),c.next())
# print(r.next(),c.next())
# print('\n')
#shape属性返回广播对象的形状
print('广播对象的形状：')
print(b)
print('\n')

#手动使用broadcast将x与y相加：
#print(c.shape)
print('\n')
#c.flat=[u + v for (u,v) in b]

print('调用flat函数')
print(c)
print('\n')

#获得了和numpy内建的广播支持相同的结果
print('x 与 y 的和：')
print(x+y)

广播对象的形状：




调用flat函数


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [160]:
# numpy.broadcast_to
# 此函数将数组广播到新形状。 它在原始数组上返回只读视图。 它通常不连续。 如果新形状不符合 NumPy 的广播规则，该函数可能会抛出ValueError
a=np.arange(4).reshape(1,4)
print('原数组：')
print(a)
print('\n')

print('调用broadcst_to函数之后：')
print(np.broadcast_to(a,(4,4)))

原数组：
[[0 1 2 3]]


调用broadcst_to函数之后：
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [3]:
# numpy.expand_dims
# 函数通过在指定位置插入新的轴来扩展数组形状。该函数需要两个参数：
# arr：输入数组
# axis：新轴插入的位置
x=np.array([[1,2],[3,4]])
print('数组x:')
print(x)
print('\n')
y=np.expand_dims(x,axis=0)
print('数组y:')
print(y)
print('\n')
print('数组 x 和 y 的形状')
print(x.shape,y.shape)
print('\n')
y=np.expand_dims(x,axis=1)
print('在位置1插入轴之后的数组y:')
print(y)
print('\n')
print(x.ndim,y.ndim)
print(x.shape,y.shape)

数组x:
[[1 2]
 [3 4]]


数组y:
[[[1 2]
  [3 4]]]


数组 x 和 y 的形状
(2, 2) (1, 2, 2)


在位置1插入轴之后的数组y:
[[[1 2]]

 [[3 4]]]


2 3
(2, 2) (2, 1, 2)


In [4]:
x=np.arange(9).reshape(1,3,3)
print('数组x:')
print(x)
print('\n')
y=np.squeeze(x)
print('数组y')
print(y)
print('\n')
print('数组 x 和 y 的形状')
print(x.shape,y.shape)

数组x:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


数组y
[[0 1 2]
 [3 4 5]
 [6 7 8]]


数组 x 和 y 的形状
(1, 3, 3) (3, 3)


In [15]:
# numpy.concatenate
# 数组的连接是指连接。 此函数用于沿指定轴连接相同形状的两个或多个数组。 该函数接受以下参数。
a=np.array([[1,2],[3,4]])
print('第一个数组')
print(a)
print('\n')

b=np.array([[5,6],[7,8]])
print('第二个数组')
print(b)
print('\n')
print('沿轴0连接两个数组：')
print(np.concatenate((a,b))
print('\n')
print('沿轴1连接两个数组;')
print(np.concatenate((a,b_),axis=1)

SyntaxError: invalid syntax (<ipython-input-15-5120f72d6741>, line 14)

In [17]:
aa=np.array([[1,2],[3,4]])
print('第一个数组')
print(a)
print('\n')
b=np.array([[5,6],[7,8]])
print('第二个数组')
print(b)
print('\n')
print('沿轴0堆叠两个数组')
print(np.stack((a,b)),0)//要转换成tuple
print('\n')

print('沿轴1堆叠两个数组')
print(np.stack((a,b)),1)

第一个数组
[[1 2]
 [3 4]]


第二个数组
[[5 6]
 [7 8]]


沿轴0堆叠两个数组
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 0


沿轴1堆叠两个数组
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 1


In [19]:
a=np.array([[1,2],[3,4]])
print('第一个数组')
print(a)
print('\n')
b=np.array([[5,6],[7,8]])
print('第二个数组')
print(b)
print('\n')
print('水平堆积')
c=np.hstack((a,b))
print(c)
print('\n')

# numpy.vstack
# numpy.stack函数的变体，通过堆叠来生成竖直的单个数组。
a=np.array([[1,2],[3,4]])
print('第一个数组')
print(a)
print('\n')

b=np.array([[5,6],[7,8]])
print('第二个数组')
print(b)
print('\n')

print('竖直堆积')
c=np.vstack((a,b))
print(c)

第一个数组
[[1 2]
 [3 4]]


第二个数组
[[5 6]
 [7 8]]


水平堆积
[[1 2 5 6]
 [3 4 7 8]]


第一个数组
[[1 2]
 [3 4]]


第二个数组
[[5 6]
 [7 8]]


竖直堆积
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
# numpy.split
# 该函数沿特定的轴将数组分割为子数组。函数接受三个参数：
# ary：被分割的输入数组
# indices_or_sections：可以是整数，表明要从输入数组创建的，等大小的子数组的数量。 如果此参数是一维数组，则其元素表明要创建新子数组的点。
# axis：默认为 0
a=np.arange(9)
print('第一个数组')
print(a)
print('\n')
print('将数组分为三个大小相等的子数组')
b=np.split(a,3)
print(b)
print('\n')

print('将数组在一维数组中表明的位置分割')
b=np.split(a,[4,7])
print(b)

第一个数组
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [21]:
# numpy.hsplit
# numpy.hsplit是split()函数的特例，其中轴为 1 表示水平分割，无论输入数组的维度是什么。
a=np.arange(16).reshape(4,4)
print('第一个数组')
print (a)
print('\n')

print('水平分割')
b=np.hsplit(a,2)
print(b)
print('\n')

第一个数组
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


水平分割
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




In [25]:
# numpy.vsplit
# numpy.vsplit是split()函数的特例，其中轴为 0 表示竖直分割，无论输入数组的维度是什么。
a=np.arange(16).reshape(4,4)
print('第一个数组')
print(a)
print('\n')
print('竖直分割')

b=np.vsplit(a,2)
print(b)
print(b[0].shape)

第一个数组
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
(2, 4)


In [26]:
# numpy.resize
# 此函数返回指定大小的新数组。 如果新大小大于原始大小，则包含原始数组中的元素的重复副本。 该函数接受以下参数。
# numpy.resize(arr, shape)
# Python
# 其中：
# arr：要修改大小的输入数组
# shape：返回数组的新形状

a=np.array([[1,2,3],[4,5,6]])
print('第一个数组')
print(a)
print('\n')

print('第一个数组的形状')
print(a.shape)
print('\n')
b=np.resize(a,(3,2))

print('第二个数组')
print(b)
print('\n')
#要注意 a 的第一行 在  b 中重复出现，因为尺寸变大了

print('修改第二个数组的大小：')
b=np.resize(a,(3,3))
print(b)


第一个数组
[[1 2 3]
 [4 5 6]]


第一个数组的形状
(2, 3)


第二个数组
[[1 2]
 [3 4]
 [5 6]]


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [29]:
# numpy.append
# 此函数在输入数组的末尾添加值。 附加操作不是原地的，而是分配新的数组。 此外，输入数组的维度必须匹配否则将生成ValueError。
# 函数接受下列函数：
# numpy.append(arr, values, axis)
# 其中：
# arr：输入数组
# values：要向arr添加的值，比如和arr形状相同(除了要添加的轴)
# axis：沿着它完成操作的轴。如果没有提供，两个参数都会被展开。
a=np.array([[1,2,3],[4,5,6]])
print('第一个数组')
print(a)
print('\n')
print('向数组添加元素')
print(np.append(a,[7,8,9]))
print('\n')

print('沿轴0添加元素')
print(np.append(a,[[7,8,9]],axis=0))
print('\n')
print('沿轴1添加元素')
print(np.append(a,[[5,5,5],[7,8,9]],axis=1))


第一个数组
[[1 2 3]
 [4 5 6]]


向数组添加元素
[1 2 3 4 5 6 7 8 9]


沿轴0添加元素
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴1添加元素
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [30]:
# numpy.insert
# 此函数在给定索引之前，沿给定轴在输入数组中插入值。 如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
# insert()函数接受以下参数：
# numpy.insert(arr, obj, values, axis)
# Python
# 其中：
# arr：输入数组
# obj：在其之前插入值的索引
# values：要插入的值
# axis：沿着它插入的轴，如果未提供，则输入数组会被展开

a=np.array([[1,2],[3,4],[5,6]])
print('第一个数组')
print(a)
print('\n')

print('未传递Axis参数。在插入之前输入数组会被展开')
print(np.insert(a,3,[111,12]))
print('\n')
print('传递了Axis参数，会广播值数组来分配输入数组')

print('沿轴0广播')
print(np.insert(a,1,[11],axis=0))
print('\n')
print('沿轴1广播')
print(np.insert(a,1,11,axis=1))

第一个数组
[[1 2]
 [3 4]
 [5 6]]


未传递Axis参数。在插入之前输入数组会被展开
[  1   2   3 111  12   4   5   6]


传递了Axis参数，会广播值数组来分配输入数组
沿轴0广播
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴1广播
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [33]:
# numpy.delete
# 此函数返回从输入数组中删除指定子数组的新数组。 与insert()函数的情况一样，如果未提供轴参数，则输入数组将展开。 该函数接受以下参数：
# Numpy.delete(arr, obj, axis)
# Python
# 其中：
# arr：输入数组
# obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
# axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
a=np.arange(12).reshape(3,4)
print('第一个数组')
print(a)
print('\n')

print('未传递Axis参数，在插入之前输入数组会被展开')
print(np.delete(a,5))
print('\n')

print('删除第二列')
print(np.delete(a,1,axis=1))

print('包含从数组中删除的替代值的切片')
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(np.delete(a,np.s_[::2]))

第一个数组
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递Axis参数，在插入之前输入数组会被展开
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第二列
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
包含从数组中删除的替代值的切片
[2 4 6 8 0]


In [34]:
# numpy.unique
# 此函数返回输入数组中的去重元素数组。 该函数能够返回一个元组，包含去重数组和相关索引的数组。 索引的性质取决于函数调用中返回参数的类型。
# numpy.unique(arr, return_index, return_inverse, return_counts)
# Python
# 其中：
# arr：输入数组，如果不是一维数组则会展开
# return_index：如果为true，返回输入数组中的元素下标
# return_inverse：如果为true，返回去重数组的下标，它可以用于重构输入数组
# return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
a=np.array([5,2,6,7,5,6,8,2,9])
print('第一个数组')
print(a)
print('\n')
print('第一个数组的去重值')
u=np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组')
u,indices=np.unique(a,return_index=True)
print (indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值')
print(a)
print('\n')

print('去重数组的下标')
u,indices=np.unique(a,return_inverse=True)
print(u)
print('\n')

print('下标为')
print(indices)
print('\n')

print('使用下标重构原数组')
print(u[indices])
print('\n')

print('返回去重元素的重复数量')
u,indices=np.unique(a,return_counts=True)
print(u)
print(indices)


第一个数组
[5 2 6 7 5 6 8 2 9]


第一个数组的去重值
[2 5 6 7 8 9]


去重数组的索引数组
[1 0 2 3 6 8]


我们可以看到每个和原数组下标对应的数值
[5 2 6 7 5 6 8 2 9]


去重数组的下标
[2 5 6 7 8 9]


下标为
[1 0 2 3 1 2 4 0 5]


使用下标重构原数组
[5 2 6 7 5 6 8 2 9]


返回去重元素的重复数量
[2 5 6 7 8 9]
[2 2 2 1 1 1]
