In [1]:
import numpy as np

In [4]:
arr1=np.arange(2,14)#生成2到14的数字，不包括14
print(arr1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [5]:
print(arr1[2])#从0开始提取,提取第2位置的值

4


In [7]:
print(arr1[0:3])#提取从0到3的值，不包括3

[2 3 4]


In [10]:
print(arr1[2:-1])#13代表的是第-1个位置，从第二个到倒数第一个的位置

[ 4  5  6  7  8  9 10 11 12]


In [12]:
print(arr1[:5])#前5个数据

[2 3 4 5 6]


In [15]:
print(arr1[-2:])#提取最后两个数据

[12 13]


In [18]:
arr2=arr1.reshape(3,4)#将矩阵arr1转化成3行4列的矩阵
print(arr2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [19]:
print(arr2[1])#取出第一行的数据

[6 7 8 9]


In [21]:
print(arr2[1][1])#取出第一行第一列的数据

7


In [22]:
print(arr2[1,2])#取出第一行第二列的数据

8


In [25]:
print(arr2[:,2])#取出第二行的数据

[ 4  8 12]


In [27]:
for i in arr2.T:#打印arr2的转置
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [28]:
for i in arr2.flat:#迭代arr2中的每个数据
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
