In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
import time
a=np.random.rand(10000000)
b=np.random.rand(10000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('vectorized version:'+ str(1000*(toc-tic))+'ms')

c=0
tic=time.time()
for i  in range(10000000):
    c+=a[i]*b[i]
    toc=time.time()
    
print(c)
print('for loop:'+str(1000*(toc-tic)) + 'ms')

2500104.14464
vectorized version:9.999752044677734ms
2500104.14464
for loop:5849.0002155303955ms


In [11]:
import numpy as np

In [12]:
a=np.random.randn(5)
print(a)

[-0.63385189 -1.08073317 -0.81697736 -2.13077061  0.982765  ]


In [13]:
print(a.shape)
print(a.size)

(5,)
5


In [14]:
print(a.T)

[-0.63385189 -1.08073317 -0.81697736 -2.13077061  0.982765  ]


In [15]:
print(np.dot(a,a.T))

7.7432148523


In [17]:
a=np.random.randn(5,1)
print(a)

[[ 0.76236025]
 [ 0.78525914]
 [ 1.29910917]
 [-0.92397937]
 [ 0.9849145 ]]


In [18]:
print(a.T)

[[ 0.76236025  0.78525914  1.29910917 -0.92397937  0.9849145 ]]


In [19]:
print(np.dot(a,a.T))

[[ 0.58119315  0.59865035  0.9903892  -0.70440515  0.75085967]
 [ 0.59865035  0.61663191  1.02013735 -0.72556324  0.77341311]
 [ 0.9903892   1.02013735  1.68768464 -1.20035008  1.27951147]
 [-0.70440515 -0.72556324 -1.20035008  0.85373788 -0.91004068]
 [ 0.75085967  0.77341311  1.27951147 -0.91004068  0.97005658]]


In [20]:
a=np.random.randn(5,1)
b=np.random.randn(1,5)
print(a)
print(b)

[[-1.94611801]
 [ 0.79117402]
 [-0.20793595]
 [ 0.15885188]
 [ 0.52258339]]
[[-0.83734992  0.30318193 -0.06416839  0.78166268 -0.11949331]]


In [23]:
assert(a.shape==(5,1))


ValueError: cannot reshape array of size 5 into shape (3,2)